LR/LR/Entities/Movie.cs
using Microsoft.Build.Framework;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using RequiredAttribute = System.ComponentModel.DataAnnotations.RequiredAttribute;


namespace LR.Entities
{
  public class Movie
  {
    public int Id { get; set; }
     
    public int? CategoryId { get; set; }
    public Category? Category { get; set; }

    [Display(Name="Title")]
    [Required]
    [StringLength(100, MinimumLength = 5)]
    public string? Title { get; set; }

    public string Description { get; set; }

    [Required]
    public int Duration { get; set; }

    [Display(Name = "Avatar")]
    [NotMapped]
    public IFormFile? Image { get; set; }

    public string? ImagePath { get; set; }

    public string? MimeType { get; set; }
  }

  public class Category
  {
    public int Id { get; set; }
    public string? Title { get; set; }

    public ICollection<Movie>? Movies{ get; set; }
  }
}

LR/LR/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LR.Data;
using LR.Entities;


namespace LR.Controllers
{
  [Controller]
  public class AdminController : Controller
  {
    private readonly MovieContext _context;
    private IWebHostEnvironment _appEnvironment;

    public AdminController(MovieContext context, IWebHostEnvironment appEnvironment) =>
      (this._context, this._appEnvironment) = (context, appEnvironment);

    // GET: Admin
    public async Task<IActionResult> Index() => View(await this._context.Movies.Include(b => b.Category).ToListAsync());


    // GET: Admin/Details/5
    public async Task<IActionResult> Details(int? id)
    {
      if (id == null || this._context.Movies == null) return NotFound();

      var movie = await this._context.Movies
          .Include(b => b.Category)
          .FirstOrDefaultAsync(m => m.Id == id);

      if (movie == null) return NotFound();


      return View(movie);
    }

    // GET: Admin/Create
    public IActionResult Create()
    {
      ViewData["Categories"] = new SelectList(_context.Categories, "Id", "Title");
      return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,CategoryId,Title,Discription,Price, Image")] Movie movie)
    {
      if (ModelState.IsValid)
      {
        if (movie.Image != null)
        {
          string path = "/images/books/" + _context.Movies.Count() + ".jpg";

          using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
          {
            await movie.Image.CopyToAsync(fileStream);
          }

          movie.ImagePath = path;
        }

        this._context.Add(movie);
        await _context.SaveChangesAsync();

        return RedirectToAction(nameof(Index));
      }
      ViewData["Categories"] = new SelectList(_context.Categories, "Id", "Title", movie.Category);

      return View(movie);
    }

    // GET: Admin/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
      if (id == null || this._context.Movies == null)
        return NotFound();

      var movie = await _context.Movies.FindAsync(id);

      if (movie == null)
        return NotFound();

      ViewData["Categories"] = new SelectList(_context.Categories, "Id", "Title", movie.Category);

      return View(movie);
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,CategoryId,Title,Description,Duration,Image")] Movie movie)
    {
      if (id != movie.Id)
        return NotFound();

      if (ModelState.IsValid)
      {
        try
        {
          if (movie.Image != null)
          {

            string? path = movie.ImagePath;
            if (path == null)
            {
              path = "/images/books/" + movie.Id + ".jpg";
              movie.ImagePath = path;
            }


            using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
            {
              await movie.Image.CopyToAsync(fileStream);
            }
          }

          _context.Update(movie);
          await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
          if (!BookExists(movie.Id))
            return NotFound();
          else
            throw;
        }

        return RedirectToAction(nameof(Index));
      }

      ViewData["Categories"] = new SelectList(_context.Categories, "Id", "Title", movie.Category);

      return View(movie);
    }

    // GET: Admin/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
      if (id == null || _context.Movies == null)
        return NotFound();

      var movie = await _context.Movies
          .Include(b => b.Category)
          .FirstOrDefaultAsync(m => m.Id == id);

      if (movie == null)
        return NotFound();

      return View(movie);
    }

    // POST: Admin/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      if (this._context.Movies == null)
        return Problem("Entity set 'MovieContext.Movies'  is null.");


      var movie = await this._context.Movies.FindAsync(id);

      if (movie != null)
      {
        if (movie.ImagePath != null)
        {
          string? path = movie.ImagePath;
          System.IO.File.Delete(_appEnvironment.WebRootPath + path);
        }

        this._context.Movies.Remove(movie);
      }

      await _context.SaveChangesAsync();
      return RedirectToAction(nameof(Index));
    }

    private bool BookExists(int id) => this._context.Movies.Any(e => e.Id == id);
  }
}

LR/LR/Controllers/MovieController.cs
using LR.Data;
using LR.Entities;
using LR.Models;
using Microsoft.AspNetCore.Mvc;


namespace LR.Controllers
{
  public class MovieController : Controller
  {
    private MovieContext _context;
    private int _amountPerPage = 4;

    public MovieController(MovieContext context) => this._context = context;

    [Route("Catalog")]
    [Route("Catalog/Page_{currentPage:int}/{group:int?}")]
    public IActionResult Index(int? group, int currentPage = 1)
    {
      ViewData["Categories"] = _context.Categories.ToList();
      ViewData["CurrentCategory"] = group ?? 0;
      var moviesCount = _context.Movies.Where(movie => movie != null && (group != null && group != 0 ? movie.Category.Id == group : true)).Count();
      //Console.WriteLine($"COUNT: {moviesCount}");
      var temp = moviesCount / _amountPerPage + 1;
      ListViewModel<Movie>.TotalPages = System.Convert.ToInt32(temp);

      var data = ListViewModel<Movie>.GetModel(_context.Movies, currentPage, movie => !group.HasValue || movie.Category.Id == group.Value);


      return Request.IsAjaxRequest() ? PartialView("_ListPartial", data) : View(data);
    }
  }
}

LR/LR/Views/Movie/Index.cshtml
@using LR.Entities
@using LR.Models
@model IEnumerable<LR.Entities.Movie>


@{
	ViewData["Title"] = "Movies List:";
	var categories = ViewData["Categories"] as IEnumerable<Category>;
	//Console.WriteLine("Vuew" + ViewData["CurrentCategory"]);
	var currentGroup = (int)ViewData["CurrentCategory"];
	var text = currentGroup != 0
		? categories.FirstOrDefault(g => g.Id == currentGroup)?.Title
		: "All";

	var pageTotal = ListViewModel<Movie>.TotalPages;
	var currentPage = ListViewModel<Movie>.CurrentPage;

	var request = ViewContext.HttpContext.Request;
	var returnUrl = request.Path + request.QueryString.ToUriComponent();
	var domain = request.Host;
}


<div class="container">
	<div class="row">
		<h1>Movies List</h1>
	</div>
	<div class="row mt-3 mb-5">
		<a asp-controller="Admin" asp-action="Create" class="btn btn-outline-primary" style=" width: auto; margin-right: auto;">Create New</a>
	</div>
	<div class="card-deck row">
		<div class="col-2">
			<div class="dropdown">
				<a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					@text
				</a>
				<div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
					@foreach (var cat in @categories)
					{
						@if (!(cat.Title == text))
						{
							<a class="dropdown-item" href="?group=@cat.Id">@cat.Title</a>
						}
					}
					@if (text != "All")
					{
						<a class="dropdown-item" asp-action="Index" asp-controller="Movie">All</a>
					}
				</div>
			</div>

		</div>
	</div>

	<div class="row mt-5" id="list">
		<partial name="_ListPartial" model="@Model" />
	</div>

	<div class="row mt-6">
		<nav aria-label="Page navigation example">
			<ul class="pagination justify-content-center">
				@for (var page = 0; page < pageTotal; ++page)
				{
					<pager action="Index"
					   controller="Movie"
					   group-id="@currentGroup"
					   page-total="@pageTotal"
					   page-current="@(page + 1)">
						@(page + 1)
					</pager>
				}

			</ul>
		</nav>
	</div>
</div>



<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript">
	function loadPageAsync(event) {
		event.preventDefault()

		const url = this.attributes["href"].value

		$('#list').load(url)

		$('.active').removeClass('active disabled')
		$(this).parent().addClass('active')

		history.pushState(null, null, url)
	}

	$(document).ready(function () {
		$('.page-link').click(loadPageAsync)
	})
</script>

LR/LR/Views/Movie/_ListPartial.cshtml
@model IEnumerable<LR.Entities.Movie>


@foreach (var item in Model)
{
	<div class="col-lg-3 col-md-4 col-sm-6 col-xs-6 col-6" style="margin-bottom:15px;">
		<partial name="_ListItemPartial" model="@item" />
	</div>
}