LR/LR/Components/MenuViewComponent.cs
using LR.Models;
using Microsoft.AspNetCore.Mvc;


namespace LR.Components
{
  [ViewComponent]
  public class MenuViewComponent : ViewComponent
  {
    private readonly List<MenuItem> _menuItems = new()
        {
            new MenuItem {Controller = "Home", Action = "Index", Text = "Lab 2"},
            new MenuItem {Controller = "Movie", Action = "Index", Text = "Catalog"},
            new MenuItem{ Controller="Admin", Action="Index", Text = "Administration" }
        };

    public IViewComponentResult Invoke()
    {
      this.Check();
      return View(this._menuItems);
    }

    private void Check()
    {
      var controller = ViewContext.RouteData.Values["controller"]?.ToString();
      var area = ViewContext.RouteData.Values["area"]?.ToString();

      foreach (var menuItem in this._menuItems)
      {
        var controllerMatch = controller != null && controller == menuItem.Controller;
        var areaMatch = area != null && area == menuItem.Area;

        if (controllerMatch || areaMatch) menuItem.Active = "ACTIVE";
      }
    }
  }
}

LR/LR/Controllers/CartController.cs
using LR.Data;
using Microsoft.AspNetCore.Mvc;
using LR.Models;
using Microsoft.AspNetCore.Authorization;
using Newtonsoft.Json;

namespace LR.Controllers
{
  [Controller]
  public class CartController : Controller
  {
    private MovieContext _context;
    private Cart _cart = new();

    public CartController(MovieContext context, Cart cart) => (this._context, this._cart) = (context, cart);

    public IActionResult Index() => View(_cart.Items.Values);


    [Authorize]
    public IActionResult Add(int id, string returnUrl)
    {
      if (HttpContext.Session.GetString("cart") != null)
        this._cart = JsonConvert.DeserializeObject<Cart>(HttpContext.Session.GetString("cart"));
      

      var movie = this._context.Movies.Find(id);

      if (movie != null)
      {
        this._cart.AddToCart(movie);
        HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(this._cart));
      }


      return Redirect(returnUrl);
    }

    [Authorize]
    public async Task<IActionResult> Delete(int id)
    {
      if (id == null || this._context.Movies == null)
        return NotFound();

      this._cart.Items.TryGetValue(id, out CartItem? item);

      if (item == null)
        return NotFound();

      return View(item);
    }

    [Authorize]
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
      if (HttpContext.Session.GetString("cart") != null)
        this._cart = JsonConvert.DeserializeObject<Cart>(HttpContext.Session.GetString("cart"));

      this._cart.RemoveFromCart(id);

      HttpContext.Session.SetString("cart", JsonConvert.SerializeObject(this._cart));

      return RedirectToAction(nameof(Index));
    }
  }
}

LR/LR/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using LR.Entities
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>@ViewData["Title"] - LR</title>
      <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

      <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
      <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
      <link rel="stylesheet" href="~/LR.styles.css" asp-append-version="true" />
    </head>
    <body style="overflow-x: hidden;">
      <header class="header">
        <div class="container">
          <nav class="navbar navbar-expand-lg">
            <div class="container-fluid" style="align-items: center;">
              <a class="navbar-brand nav-brand-header" asp-action="Index" asp-controller="Home">ASP.NET labs</a>
              @await Component.InvokeAsync("Menu")


              <partial name="_LoginPartial" />

              @if (SignInManager.IsSignedIn(User)) {
              <partial name="_UserPartial" />
                }

            </div>
          </nav>
        </div>
      </header>

      <main class="main">@RenderBody()</main>

      <footer class="my-footer">
        <div class="container">
          <div class="d-flex footer-links">
            <a href="https://facebook.com" target="new">
              <i class="fa-brands fa-facebook fa-2xl footer-icons"></i>
            </a>
            <a href="https://vk.com" target="new">
              <i class="fa-brands fa-vk fa-2xl footer-icons"></i>
            </a>
            <a href="https://twitter.com" target="new">
              <i class="fa-brands fa-twitter fa-2xl footer-icons"></i>
            </a>
          </div>
        </div>
      </footer>


      <script src="~/lib/jquery/dist/jquery.js"></script>
      <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
      <script src="~/js/site.js" asp-append-version="true"></script>
      @await RenderSectionAsync("Scripts", required: false)
    </body>
  </html>

LR/LR/Views/Shared/_ListItemPartial.cshtml
@{
	var request = ViewContext.HttpContext.Request;
	var returnUrl = request.Path + request.QueryString.ToUriComponent();
	var domain = request.Host;
}


<article class="card">
	<div class="card-body" style="text-align:center;">
		<img src="https://@domain/@Model.ImagePath" style="height:333px; width:100%; object-fit: cover; border-radius: 5px;" />
		<h1 class="card-title mt-2" style="font-size: 20px;">@Model.Title</h1>
		<p class="card-text">@Model.Description</p>
		<h3 class="card-subtitle badge">@Model.Duration</h3>
		<a asp-action="Add" asp-controller="Cart" asp-route-id="@Model.Id" asp-route-returnUrl="@returnUrl" class="btn btn-outline-primary" style="width: 100%;">
			<i class="fa fa-shopping-cart"></i> To Cart
		</a>
	</div>
</article>

LR/LR/Views/Shared/_UserPartial.cshtml
<div class="d-flex" role="search" style="align-items: center;">
    @await Component.InvokeAsync("Cart")

    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" style="background-color: white;" type="button" data-bs-toggle="dropdown"
              aria-expanded="false">
       <image img-action="GetImage" img-controller="LoadPicture" />
      
      </button>
        <ul class="dropdown-menu">
            <li class="dropdown-user-info">
                <span>user@mail.com</span>
                <img src="@Url.Action("GetImage", "LoadPicture")" alt="Profile logo" width="16">
            </li>
            <li>
                <a class="dropdown-item" asp-controller="Product" asp-action="UserProducts">My goods</a>
            </li>
            <li>
              <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@ViewContext.HttpContext.Request.Path">
                <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout">Log out</a>
              </form>
            </li>
        </ul>
    </div>
</div>